# Generated by Django 4.0.4 on 2022-07-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontur_mailey', '0002_emails_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtername',
            options={},
        ),
        migrations.RemoveField(
            model_name='filtername',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filtername',
            name='need_to_send',
        ),
        migrations.RemoveField(
            model_name='filtername',
            name='target',
        ),
    ]
