# Generated by Django 4.0.4 on 2022-07-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontur_mailey', '0005_alter_emails_options_filtername_need_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtername',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters', to='kontur_mailey.target'),
        ),
    ]
