# Generated by Django 4.0.3 on 2022-05-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Сотрудник тендерного отдела',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя менеджера')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todolist.department')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='TenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Категория процедуры',
                'verbose_name_plural': 'Категории процедур',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('nominal_max_price', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='НМЦ')),
                ('review_status', models.BooleanField(blank=True, null=True, verbose_name='Статус рассмотрения')),
                ('submit_date', models.DateTimeField(verbose_name='Дата подачи')),
                ('process_date', models.DateTimeField(verbose_name='Дата процедуры')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Цена участия')),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='Результат')),
                ('comment', models.TextField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('importance', models.BooleanField(blank=True, null=True, verbose_name='Статус важности')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todolist.author', verbose_name='Сотрудник тендерного отдела')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todolist.currency', verbose_name='Валюта')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todolist.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Закупочная процедура',
                'verbose_name_plural': 'Закупочные процедуры',
                'ordering': ['-created_date'],
            },
        ),
    ]
