# Generated by Django 4.0.4 on 2022-05-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todolist.currency', verbose_name='Валюта'),
        ),
    ]
