# Generated by Django 4.0.4 on 2022-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='nominal_max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='НМЦ'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена участия'),
        ),
    ]
